config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  root "publishers#index"
  resources :publishers
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :book_authors
  has_many :books, through: :book_authors

  validates :name, presence: true, uniqueness: true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :publisher
  has_many :book_authors
  has_many :authors, through: :book_authors
  has_many :book_issues
  has_many :book_requests

  validates :title, :category_name, presence: true
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :book
  belongs_to :author
  # validates :book_id, presence: true
  # validates :author_id, presence: true
  # validates_uniqueness_of :author_id, scope: :book_id
end

app/models/book_issue.rb
class BookIssue < ApplicationRecord
  belongs_to :book
  belongs_to :member
  belongs_to :library_staff

  validates :issue_date, :return_date, presence: true

end

app/models/book_request.rb
class BookRequest < ApplicationRecord
  belongs_to :book
  belongs_to :member

  validates :request_date, presence: true
end

app/models/fine_payment.rb
class FinePayment < ApplicationRecord
  # belongs_to :fine
  belongs_to :member # this fine belongs to this(which so ever member present) member_id


  validates :fine_due_date, :payment_date, :payment_amount, presence: true
  # validates :amount, presence: true
  # validates :amount, numericality: { greater_than: 0 }
  # validates :user_id, presence: true
  # validates :fine_id, presence: true
  # validate :amount_cannot_be_greater_than_fine_amount

  # def amount_cannot_be_greater_than_fine_amount
  #   if amount > fine.amount
  #     errors.add(:amount, "can't be greater than fine amount")
  #   end
  # end
end

app/models/library_staff.rb
class LibraryStaff < ApplicationRecord
  has_many :book_issues

  validates :name, :designation, presence: true
end

app/models/member.rb
class Member < ApplicationRecord

  after_validation -> { puts "Congratulations! registration successful !" }
  # after_commit :send_welcome_message

  has_one :fine_payment # one member has to pay a fine_payment
  has_many :book_requests
  has_many :book_issues

  validates :first_name, :last_name, :city, presence: true
  # validates :mobile_no, length: { is: 10 }, uniqueness: true, presence: true
  # validates :mobile_no, presence: true, uniqueness: true


  # private
  #   def send_welcome_message
  #     puts "\n\n Welcome, #{first_name}! Your registration was successful.\n\n"
  #   end
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books, dependent: :destroy

  validates :name, :language, :year, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]


  # GET /books
  def index
    @books = Book.all

    render json: @books
  end

  # GET /books/1
  def show
    render json: @book
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit

  end

  # POST /books
  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book, notice: 'Book was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /books/1
  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /books/1
  def destroy
    @book.destroy
    # redirect_to books_url, notice: 'Book was successfully destroyed.'
  end

  private
    # Using callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allowing a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :category_name, :publisher_id)
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :set_publisher, only: [:show, :edit, :update, :destroy]


  # GET /publishers
  def index
    @publishers = Publisher.all
    respond_to do |format|
      format.html
      format.json { render json: @publishers }
    end
  end

  # GET /publishers/1
  def show
    # render json: @publisher
  end

  # GET /publishers/new
  def new
    @publisher = Publisher.new
  end

  # GET /publishers/1/edit
  def edit

  end

  # POST /publishers
  def create
    @publisher = Publisher.new(publisher_params)

    if @publisher.save
      redirect_to action: :index
    else
      render :new
    end
  end

  # PATCH/PUT /publishers/1
  def update
    @publisher.update(publisher_params)
    if @publisher.save
      redirect_to action: :index
    else
      render :edit
    end
  end

  # DELETE /publishers/1
  def destroy
    @publisher.destroy
    # redirect_to root_path, status: :see_other
  end

  private
    # Using callbacks to share common setup or constraints between actions.
    def set_publisher
      @publisher = Publisher.find(params[:id])
    end

    # Only allowing a list of trusted parameters through.
    def publisher_params
      params.require(:publisher).permit(:name, :language, :year)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibMgmt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/publishers/edit.html.erb
<h1> Edit publisher </h1>

<%= form_for(@publisher) do |f| %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <br>

    <div>
        <%= f.label :language %>
        <%= f.text_field :language %>
    </div>

    <br>

    <div>
        <%= f.label :year %>
        <%= f.text_field :year %>
    </div>

    <br>

    <%= f.submit  "Edit publisher" %>
    <%= link_to "Back to list",publishers_path %>
<% end %>

app/views/publishers/index.html.erb
<h1>Publishers</h1>


    <ul>
        <% @publishers.each do |u| %>
          <li> 
            <%= link_to u.name, publisher_path(u) %>
            <%= button_to "Edit", edit_publisher_path(u), method: :get %>
            <%= button_to "Delete", publisher_path(u), method: :delete %>
          </li>
    </ul>
<% end %>

<p>
    <%= link_to "Add new publisher: ", {action: 'new'} %>
</p>

app/views/publishers/new.html.erb
<h1>Create Publisher</h1>
<%= form_for(@publisher) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <br>
  <div>
    <%= f.label :language %>
    <%= f.text_field :language %>
  </div>
  <br>
  <div>
    <%= f.label :year %>
    <%= f.number_field :year %>
  </div>
  <br>
  <%= f.submit 'Create' %>
  <%= link_to 'Back', publishers_path %> 
<% end %>

app/views/publishers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @publisher.name %>
</p>

<p>
  <strong>Language:</strong>
  <%= @publisher.language %>
</p>

<p>
  <strong>Year:</strong>
  <%= @publisher.year %>
</p>

<%= link_to 'Edit', edit_publisher_path(@publisher) %> |
<%= link_to 'Back', publishers_path %>